travis:
  secure:
    BINSTAR_TOKEN: YWyJCueUomICoGrBPhtHHjz9JLO0DzpEF8PB20UhWJfZVVh9sg2qxsp3wJo9tIP3SPa0bTAxEQYvR8huvoexyrIsiZxXat6C4t3Y7h/HCekIXyz5Vv5ckAyi9K2RWzTZmpGeIEiWL4ok3VntVsDj2h+sgiXHynGcjyve/X3bJ0Cb7ccbDOcTzGjz5feC91Uh4XFxyN6rYFpY21239yfxXVEqZp2oAWKMACvNZ44PSb61ModoZsb852LmbsIjULPlPG43MwrJX/1B9OXDKfhqfYNsyBwEGxvbjFIR/sGdcMETrAXelBuZm5345KiEZrRQbEs+iH7cysQM/ci7DqE5lgjv2QHT2BCQ6V3WZZdltkSFSKko01jDaAKC0DovV6RrCe7+rERGAVOfG5jnIYXPujwQHNsSdsTc6HAKnXWf67V7AUKOj2XeS1EV5g+sKLZELBtBUJw4SpnA+Cve/fqn6kScZIIQw6Yj2+HmBS+yTLaJ6PRmv2iQ2LvU9m1Bt++pgC479mP+RgK1OgpABD6pod9y4L49bVH+FUKcUr3qnsawkbVzVPNOXZUFb/glNkfCHTa8e0ctQ+6DmVMSdByB4hJKg3Uv0O7wZzKMhU1TZBce8KjxFP2CkWlE0+jM8FHK0fDQdCHBsgvar3zlDs2D+abKaP9nGK6p06DdmqFP68Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
