travis:
  secure:
    BINSTAR_TOKEN: MtonvHUxe0nYl3UYa/nt9kiDLPZZUXkfA9HWBaKfcqEmrVcxEQ5mYijyBJaMtjUjKmJNdgVGylYf/fNTWbX5UZfDA6LoY4UfkzxguDx5S1sQZwLYdO+G9OajPBWLmr/r7oeLdvDvIcf8qYMJgtezh7XmcgFDvjAzIzxJsHL10WK5SL01mRxZ4XrSFkLvKhqx/AWfzJisVL2ba+XtI5HzSH5fuheVJrqoA2kgz1IbwSfjFgHrCOzJn1GWH5cfPu48p4KhhlgYpmGYMsJa/I9qIaxqmfB700YvierNDpfW+cJdCis00Osoq0UUt5W1zHApNAvC2N3sRgq5a13m01BSHF77UROaoLFmId2z7Lk/W7OQKyktJdLXA/eAYX4dpBSLdZ9Hu+6NfnyOG91zBc+pZgGteHBrW8Pb2iu2iV64pYc6wamMBzDawNyc7DXAOHTun31bM1Gw6Q/IqmQ6ChTNQk7j89zkhOLPnF3kWzjCK0oSmt3y2X+QZYwwibzLJzKdxJKRFn9K7Zv5REWmAk2hey34H6huAytvqWls+Qwg/8KAMw2CgZPhmhm7bXpFWzBGqZ6EmOzSsYO4TQYgNCUaKheiGm/nzhcKRMeDSak7kcqHjCxSTF19rJFuics7rQdDfcPnUhlGz6O1ZFp2kc190pf3TKsi0khiDLxfIaKgkYA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
