travis:
  secure:
    BINSTAR_TOKEN: gDEXpBbAzD8OnRZ561CBSQg9/D3NH1LT5vg/iNODsDX8VMMcZmOy4b3Uh4zjU2y3kR9MpPjh3bWJZLhCdg/EU6WRBwf95mtcMDCqeYy/NpPlxr/862WovXi2ADNmpV/G7eMnGy8DhmlOLihSsC1KU0auVS/1n7FYlIt1yrAoAP8rELqd7EGyh7Fm0ihbnNY/sqW0AsCnFTh3Zw3DvLbpd+L8smPesnfNgy0yOU4Ded6ia6avbTnUvVVsy2QJJ9fgufVCie4fW8EPeGqbs0jqmhRoMv8DXkCrhjh6+GwOJpYGqM6xlXlpKV8GHp01bevVc9zHXImJgtqLT6fjM/VqhaLV9ZGbrApIsThCpjQGpdtnjD8xq3KisDpMkibZkMYWkuw+y8k54/VlBk8X/UlT6y5fcDnF4toFmZ7WRXnV5N0wXbh/CgATHy2uWkwbSryFAww33V8wT+qqiGoHbSN5IP2ZSkAEh3mJSRDlljmpbV/RtTqiQJ6yBmfKw6fJ3i3cfs+CrArVvgs50uBnDIUpiK8kYHlSEh7ImH4EGt3kaNxIUe/yBYzfpYVe6Sh2neBslzVUOadZyA2t7RAu2Fv2wNhd8fzkNw5SeICb7BpvXJrFQSIqpPwrTLMJVWafnkOH8GHu/oTkTxjCE+alkc1iXEpbUR5aCzz/C1f33cLVovw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
